import 'dart:typed_data';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfHelper {
  static Future<void> saveResultPdf(int score) async {
    final doc = pw.Document();
    doc.addPage(
      pw.Page(
        build: (context) => pw.Column(children: [
          pw.Text('Hasil Screening', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 12),
          pw.Text('Score: $score'),
          pw.SizedBox(height: 8),
          pw.Text('Generated by InsightMind'),
        ]),
      ),
    );

    final Uint8List bytes = await doc.save();
    await Printing.sharePdf(bytes: bytes, filename: 'hasil_screening.pdf');
  }
}
